### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by cakiki** [genaibook/genaibook#21]
Countains -> Contains

**Comment by pcuenca** [comment]
cc @osanseviero, I don't have access to the repo settings :)

<img width="270" alt="Screenshot 2024-11-18 at 10 03 03" src="https://github.com/user-attachments/assets/d84fd2ab-ff4d-438d-803c-45926ee79c48">

**Comment by osanseviero** [comment]
You should have acces now, thanks!
